# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diag_selection_mat <- function(n) {
    .Call('_BEKKs_diag_selection_mat', PACKAGE = 'BEKKs', n)
}

set_seed <- function(seed) {
    invisible(.Call('_BEKKs_set_seed', PACKAGE = 'BEKKs', seed))
}

elimination_mat <- function(n) {
    .Call('_BEKKs_elimination_mat', PACKAGE = 'BEKKs', n)
}

commutation_mat <- function(n) {
    .Call('_BEKKs_commutation_mat', PACKAGE = 'BEKKs', n)
}

duplication_mat <- function(n) {
    .Call('_BEKKs_duplication_mat', PACKAGE = 'BEKKs', n)
}

inv_gen <- function(m) {
    .Call('_BEKKs_inv_gen', PACKAGE = 'BEKKs', m)
}

valid_bekk <- function(C, A, G) {
    .Call('_BEKKs_valid_bekk', PACKAGE = 'BEKKs', C, A, G)
}

expected_indicator_value <- function(r, signs) {
    .Call('_BEKKs_expected_indicator_value', PACKAGE = 'BEKKs', r, signs)
}

valid_asymm_bekk <- function(C, A, B, G, r, signs) {
    .Call('_BEKKs_valid_asymm_bekk', PACKAGE = 'BEKKs', C, A, B, G, r, signs)
}

valid_asymm_bekk_sim <- function(C, A, B, G, exp_indicator_value, signs) {
    .Call('_BEKKs_valid_asymm_bekk_sim', PACKAGE = 'BEKKs', C, A, B, G, exp_indicator_value, signs)
}

loglike_bekk <- function(theta, r) {
    .Call('_BEKKs_loglike_bekk', PACKAGE = 'BEKKs', theta, r)
}

loglike_asymm_bekk <- function(theta, r, signs) {
    .Call('_BEKKs_loglike_asymm_bekk', PACKAGE = 'BEKKs', theta, r, signs)
}

score_bekk <- function(theta, r) {
    .Call('_BEKKs_score_bekk', PACKAGE = 'BEKKs', theta, r)
}

score_dbekk <- function(theta, r) {
    .Call('_BEKKs_score_dbekk', PACKAGE = 'BEKKs', theta, r)
}

score_asymm_bekk <- function(theta, r, signs) {
    .Call('_BEKKs_score_asymm_bekk', PACKAGE = 'BEKKs', theta, r, signs)
}

bhh_bekk <- function(r, theta, max_iter, crit) {
    .Call('_BEKKs_bhh_bekk', PACKAGE = 'BEKKs', r, theta, max_iter, crit)
}

bhh_asymm_bekk <- function(r, theta, max_iter, crit, signs) {
    .Call('_BEKKs_bhh_asymm_bekk', PACKAGE = 'BEKKs', r, theta, max_iter, crit, signs)
}

random_grid_search_BEKK <- function(r) {
    .Call('_BEKKs_random_grid_search_BEKK', PACKAGE = 'BEKKs', r)
}

random_grid_search_asymmetric_BEKK <- function(r, signs) {
    .Call('_BEKKs_random_grid_search_asymmetric_BEKK', PACKAGE = 'BEKKs', r, signs)
}

sigma_bekk <- function(r, C, A, G) {
    .Call('_BEKKs_sigma_bekk', PACKAGE = 'BEKKs', r, C, A, G)
}

sigma_bekk_asymm <- function(r, C, A, B, G, signs) {
    .Call('_BEKKs_sigma_bekk_asymm', PACKAGE = 'BEKKs', r, C, A, B, G, signs)
}

hesse_bekk <- function(theta, r) {
    .Call('_BEKKs_hesse_bekk', PACKAGE = 'BEKKs', theta, r)
}

hesse_asymm_bekk <- function(theta, r, signs) {
    .Call('_BEKKs_hesse_asymm_bekk', PACKAGE = 'BEKKs', theta, r, signs)
}

eigen_value_decomposition <- function(A) {
    .Call('_BEKKs_eigen_value_decomposition', PACKAGE = 'BEKKs', A)
}

simulate_bekk_c <- function(theta, NoObs, n) {
    .Call('_BEKKs_simulate_bekk_c', PACKAGE = 'BEKKs', theta, NoObs, n)
}

simulate_bekka_c <- function(theta, NoObs, n, signs, expected_signs) {
    .Call('_BEKKs_simulate_bekka_c', PACKAGE = 'BEKKs', theta, NoObs, n, signs, expected_signs)
}

indicatorFunction <- function(r, signs) {
    .Call('_BEKKs_indicatorFunction', PACKAGE = 'BEKKs', r, signs)
}

valid_scalar_bekk <- function(a, b) {
    .Call('_BEKKs_valid_scalar_bekk', PACKAGE = 'BEKKs', a, b)
}

loglike_scalar_bekk <- function(theta, r) {
    .Call('_BEKKs_loglike_scalar_bekk', PACKAGE = 'BEKKs', theta, r)
}

score_scalar_bekk <- function(theta, r) {
    .Call('_BEKKs_score_scalar_bekk', PACKAGE = 'BEKKs', theta, r)
}

bhh_scalar_bekk <- function(r, theta, max_iter, crit) {
    .Call('_BEKKs_bhh_scalar_bekk', PACKAGE = 'BEKKs', r, theta, max_iter, crit)
}

hesse_scalar_bekk <- function(theta, r) {
    .Call('_BEKKs_hesse_scalar_bekk', PACKAGE = 'BEKKs', theta, r)
}

YLagCr <- function(y, p) {
    .Call('_BEKKs_YLagCr', PACKAGE = 'BEKKs', y, p)
}

