# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SigmaGARCHuniv <- function(param, Tob, SigmaE, est) {
    .Call('_BEKKs_SigmaGARCHuniv', PACKAGE = 'BEKKs', param, Tob, SigmaE, est)
}

YLagCr <- function(y, p) {
    .Call('_BEKKs_YLagCr', PACKAGE = 'BEKKs', y, p)
}

YLagCr0 <- function(r2, Tob, q, m_r2) {
    .Call('_BEKKs_YLagCr0', PACKAGE = 'BEKKs', r2, Tob, q, m_r2)
}

